StringTable {
 TargetPrefix "Target_"
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{59BAA89A213B215F}" {
   Id "GREG-Equipement_NightVision_decrease_luminosity"
   Target_en_us "Decrease luminosity - Night vision"
   Target_fr_fr "Diminuer luminosité - Vision nocturne"
   Target_es_es "Regulación - Visión nocturna"
   Target_cs_cz "Stmívání - noční vidění"
   Target_zh_cn "调光 - 夜视"
   Modified 1505408089
   Author "gregfr_3d"
   LastChanged "Greg"
  }
  CustomStringTableItem "{59BAB58A350240C3}" {
   Id "GREG-Equipement_NightVision_helmet"
   Target_en_us "Helmet - Night Vision"
   Target_fr_fr "Casque - vision nocturne"
   Target_es_es "Casco - Visión nocturna"
   Target_cs_cz "Přilba - noční vidění"
   Target_zh_cn "头盔 - 夜视"
   Modified 1505416605
   Author "Greg"
   LastChanged "Greg"
  }
  CustomStringTableItem "{59BAA8994E518812}" {
   Id "GREG-Equipement_NightVision_increase_luminosity"
   Target_en_us "Increase luminosity - Night vision"
   Target_fr_fr "Augmenter luminosité - Vision nocturne"
   Target_es_es "Aumento de la luminosidad - Visión nocturna"
   Target_cs_cz "Zvýšení jasu - Noční vidění"
   Target_zh_cn "增加亮度 - 夜视"
   Modified 1505408068
   Author "gregfr_3d"
   LastChanged "Greg"
  }
  CustomStringTableItem "{59BAA54BB72FA5D0}" {
   Id "GREG-Equipement_NightVision_toggle"
   Target_en_us "Toggle - Night vision"
   Target_fr_fr "Allumer/Éteindre - Vision nocture"
   Target_es_es "On/Off - Visión nocturna"
   Target_cs_cz "Zapnuto/vypnuto - Noční vidění"
   Target_zh_cn "开/关 - 夜视"
   Modified 1505408045
   Author "gregfr_3d"
   LastChanged "Greg"
  }
 }
}